✨ Rate limit, tests and scripts
Add rate limit at 200 per two minutes. Updat

diff --git a/test_scripts/delete_registration b/test_scripts/delete_registration
--- a/test_scripts/delete_registration
+++ b/test_scripts/delete_registration
@@ -2,36 +2,36 @@
 
 host=http://echo-web-backend.herokuapp.com
 
-while getopts zp:s:e:x: flag
-do
-    case "${flag}" in
-        z) host=http://localhost;;
-        p) port=${OPTARG};;
-        s) slug=${OPTARG};;
-        e) email=${OPTARG};;
-        x) secret=${OPTARG};;
-    esac
+while getopts zp:s:e:x: flag; do
+  case "${flag}" in
+  z) host=http://localhost ;;
+  p) port=${OPTARG} ;;
+  s) slug=${OPTARG} ;;
+  e) email=${OPTARG} ;;
+  x) secret=${OPTARG} ;;
+  *) echo "Invalid flag." ;;
+  esac
 done
 
 if [ -z ${secret+x} ]; then
-    echo "No authorization header specified (use -x)"
-    exit 1;
+  echo "No authorization header specified (use -x)"
+  exit 1
 fi
 
 if [ -z ${port+x} ]; then
-    echo "Port not defined (use -p)";
-    exit 1;
+  echo "Port not defined (use -p)"
+  exit 1
 fi
 
 if [ -z ${slug+x} ] || [ -z ${email+x} ]; then
-    echo "Slug and/or email not defined (use -s and -e)";
-    exit 1;
+  echo "Slug and/or email not defined (use -s and -e)"
+  exit 1
 else
-    curl --verbose \
+  curl --verbose \
     -X DELETE \
     -H "Authorization: $secret" \
     -H "Connection: close" \
     -H "Content-Type: application/json" \
     -d '{ "slug": "'${slug}'", "email": "'${email}'" }' \
-    "$host:$port/registration";
+    "$host:$port/registration"
 fi
diff --git a/test_scripts/get_registrations b/test_scripts/get_registrations
--- a/test_scripts/get_registrations
+++ b/test_scripts/get_registrations
@@ -2,41 +2,41 @@
 
 host=https://echo-web-backend.herokuapp.com
 
-while getopts zp:e:s:x: flag
-do
-    case "${flag}" in
-        z) host=http://localhost;;
-        p) port=${OPTARG};;
-        e) email=${OPTARG};;
-        s) slug=${OPTARG};;
-        x) secret=${OPTARG};
-    esac
+while getopts zp:e:s:x: flag; do
+  case "${flag}" in
+  z) host=http://localhost ;;
+  p) port=${OPTARG} ;;
+  e) email=${OPTARG} ;;
+  s) slug=${OPTARG} ;;
+  x) secret=${OPTARG} ;;
+  *) echo "Invalid flag." ;;
+  esac
 done
 
 if [ -z ${secret+x} ]; then
-    echo "No authorization header specified (use -x)."
-    exit 1;
+  echo "No authorization header specified (use -x)."
+  exit 1
 fi
 
 if [ -z ${port+x} ]; then
-    echo "Port not defined (use -p)";
-    exit 1;
+  echo "Port not defined (use -p)"
+  exit 1
 fi
 
 if [ -z ${email+x} ] && [ -z ${slug+x} ]; then
-    curl --verbose \
+  curl --verbose \
     -H "Authorization: $secret" \
     $host:$port/registration
 elif [ -z ${slug+x} ]; then
-    curl --verbose \
+  curl --verbose \
     -H "Authorization: $secret" \
     $host:$port/registration?email=$email
 elif [ -z ${email+x} ]; then
-    curl --verbose \
+  curl --verbose \
     -H "Authorization: $secret" \
     "$host:$port/registration?slug=$slug"
 else
-    curl --verbose \
+  curl --verbose \
     -H "Authorization: $secret" \
     "$host:$port/registration?email=$email&slug=$slug"
 fi
diff --git a/test_scripts/submit_bedpres b/test_scripts/submit_bedpres
--- a/test_scripts/submit_bedpres
+++ b/test_scripts/submit_bedpres
@@ -2,45 +2,45 @@
 
 host=http://echo-web-backend.herokuapp.com
 
-while getopts zp:s:o:r:x: flag
-do
-    case "${flag}" in
-        z) host=http://localhost;;
-        p) port=${OPTARG};;
-        s) slug=${OPTARG};;
-        o) spots=${OPTARG};;
-        r) regdate=${OPTARG};;
-        x) secret=${OPTARG};;
-    esac
+while getopts zp:s:o:r:x: flag; do
+  case "${flag}" in
+  z) host=http://localhost ;;
+  p) port=${OPTARG} ;;
+  s) slug=${OPTARG} ;;
+  o) spots=${OPTARG} ;;
+  r) regdate=${OPTARG} ;;
+  x) secret=${OPTARG} ;;
+  *) echo "Invalid flag." ;;
+  esac
 done
 
 if [ -z ${secret+x} ]; then
-    echo "No authorization header specified (use -x)"
-    exit 1;
+  echo "No authorization header specified (use -x)"
+  exit 1
 fi
 
 if [ -z ${port+x} ]; then
-    echo "Port not defined (use -p)";
-    exit 1;
+  echo "Port not defined (use -p)"
+  exit 1
 fi
 
-if [ -z ${slug+x} -a -z ${spots+x} ]; then
-    echo "Slugs and spots not defined (use -s and -o)";
-    exit 1;
+if [ -z ${slug+x} ] && [ -z ${spots+x} ]; then
+  echo "Slugs and spots not defined (use -s and -o)"
+  exit 1
 elif [ -z ${slug+x} ]; then
-    echo "Slug not defined (use -s)";
-    exit 1;
+  echo "Slug not defined (use -s)"
+  exit 1
 elif [ -z ${spots+x} ]; then
-    echo "Spots not defined (use -o)";
-    exit 1;
+  echo "Spots not defined (use -o)"
+  exit 1
 elif [ -z ${regdate+x} ]; then
-    echo "RegistrationDate not defined (use -r)";
+  echo "RegistrationDate not defined (use -r)"
 else
-    curl --verbose \
+  curl --verbose \
     -X PUT \
     -H "Authorization: $secret" \
     -H "Connection: close" \
     -H "Content-Type: application/json" \
     -d '{ "slug": "'${slug}'", "spots": '${spots}', "registrationDate": "'${regdate}'" }' \
-    $host:$port/bedpres;
+    $host:$port/bedpres
 fi
